### ISSUE TITLE
node 환경에서 사용시 오류

### ISSUE THREAD

**Issue by min9nim** [madup-inc/lever-utils#2]
node 터미널에서 require 시  오류

```
➜  lever-contents-api git:(develop) node
Welcome to Node.js v12.18.2.
Type ".help" for more information.
> 
> require('@madup-inc/utils')
Uncaught:
Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/index.modern.js" defined in the package config /Users/mac9/project/madup/lever-contents-api/node_modules/@madup-inc/utils/package.json; targets must start with "./"
    at resolveExportsTarget (internal/modules/cjs/loader.js:541:13)
    at applyExports (internal/modules/cjs/loader.js:454:14)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at repl:1:1
    at Script.runInThisContext (vm.js:120:20) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
> 
```

node 서버(lever-contents-api) 구동시 오류
```
/usr/local/bin/node /usr/local/Cellar/yarn/1.21.1/libexec/bin/yarn.js run dev
yarn run v1.21.1
$ ts-node src/index.ts
Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/index.modern.js" defined in the package config /Users/mac9/project/madup/lever-contents-api/node_modules/@madup-inc/utils/package.json; targets must start with "./"
    at resolveExportsTarget (internal/modules/cjs/loader.js:541:13)
    at applyExports (internal/modules/cjs/loader.js:454:14)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/mac9/project/madup/lever-contents-api/src/env/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

**Comment by min9nim** [comment]
오잉? 집에서 하니까 잘된다?...

```

➜  lever-contents-api git:(develop) node                                         
Welcome to Node.js v12.14.1.
Type ".help" for more information.
> require('@madup-inc/utils')
{
  classNames: [Function],
  isNil: [Function: e],
  isNotNil: [Function: r],
  oneOf: [Function],
  parseSearchParams: [Function],
  randomStr: [Function],
  serializeSearchParams: [Function],
  validateBiznum: [Function]
}
> 

```

**Comment by min9nim** [comment]
윌리는 마찬가지 오류라고 함
![image](https://user-images.githubusercontent.com/6068828/121848547-28631c00-cd25-11eb-89cb-5af9b373236b.png)

혹시 노드 버젼에 따라 결과가 달라지나..  ?

**Comment by min9nim** [comment]
로컬PC 노드버젼 올리고 나니 다시 오류 발생하네요;

```
node   
Welcome to Node.js v14.17.0.
Type ".help" for more information.
> require('@madup-inc/utils')
Uncaught:
Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/index.modern.js" defined in the package config /Users/mac9/project/madup/lever-contents-api/node_modules/@madup-inc/utils/package.json; targets must start with "./"
    at throwInvalidPackageTarget (internal/modules/esm/resolve.js:309:9)
    at resolvePackageTargetString (internal/modules/esm/resolve.js:337:5)
    at resolvePackageTarget (internal/modules/esm/resolve.js:374:12)
    at packageExportsResolve (internal/modules/esm/resolve.js:475:22)
    at resolveExports (internal/modules/cjs/loader.js:437:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
> 

```

**Comment by qowns8** [comment]
노드 버전 어제 코딩하다 올린건데 저는 그전에도 오류 났으니 버전이랑은 상관 없을거 같아요

**Comment by min9nim** [comment]
cc)
https://nodejs.org/docs/latest-v14.x/api/esm.html
https://rollupjs.org/guide/en/#introduction
https://velog.io/@velopert/bundle-with-rollup-and-publish-to-npm

**Comment by min9nim** [comment]
node v12.14.1 에서는 정상동작

**Comment by min9nim** [comment]
package.json 에 "type": "module" 을 넣으면 될 것 같은데.. 해당 설정 추가하면 빌드시 오류 발생

```

> @madup-inc/utils@0.7.0 build /Users/mac9/project/madup/lever-utils
> microbundle

(babel plugin) ReferenceError: /Users/mac9/project/madup/lever-utils/babel.config.js: Error while loading config - module is not defined
ReferenceError: /Users/mac9/project/madup/lever-utils/babel.config.js: Error while loading config - module is not defined
    at file:///Users/mac9/project/madup/lever-utils/babel.config.js:1:1
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @madup-inc/utils@0.7.0 build: `microbundle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @madup-inc/utils@0.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac9/.npm/_logs/2021-06-17T09_52_10_832Z-debug.log

Process finished with exit code 1

```

**Comment by min9nim** [comment]
1. node 12.14.1 에서는 cjs 포맷(dist/index.js) 를 로드하기 때문에 오류가 발생하지 않았지만, node 14(정확히 어느 버젼부터 인지까지는 확인 안함)에서는 dist/index.modern.js 를 로드하기 때문에 발생하는 문제
2. node 특정 버젼(13예상)에서부터 esm 사용이 가능해짐. esm 을 사용하기 위해선 확장자를 .mjs 로 사용하거나 해당 모듈의 package.json 에서 `"type": "module"` 설정을 추가해야만 함. 아니면 node CLI 의 옵션으로도 가능한 것으로 알고 있음
    - 노드에서 굳이 esm 을 쓰고 싶다면 위와 같은 번거로운 설정이 필요한 것임
3. 그런데 현재 위와 같이 추가적인 설정을 한 것도 아닌데, Node14 에서 index.modern.js 파일을 로드하고 있음.
    - 아마도  package.json 에 "exports": "dist/index.modern.js" 설정이 들어있기 때문으로 보임
    - "exports" 설정을 제거하니 정상동작함을 확인
    - 프론트 프로젝트에서도 정상동작 확인함


결론) 정확한 솔루션은 아닐 수 있지만,  package.json 에서 "exports" 설정을 제거하면 Node14, 프론트프로젝트, Node12 모두에서 정상동작함

**Comment by min9nim** [comment]
1. 엔트리포인트를 결정하는 설정은 main 과 export 2개임 https://nodejs.org/api/packages.html#packages_main_entry_point_export
    - export 가 main 보다 우선순위가 높음
1. exports 설정은 Node 12.7.0 에서 도입됨 https://nodejs.org/docs/latest-v12.x/api/packages.html#packages_exports
    - 따라서 Node 12.7.0+ 버젼에서는 exports 설정을 바라보며 동작함
1. exports 를 이용해 조건별 엔트리포인트 설정 가능 https://nodejs.org/api/packages.html#packages_conditional_exports
